/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#6366F1';
const tintColorDark = '#8B5CF6';

export const Colors = {
  light: {
    text: '#0F172A',
    textSecondary: '#475569',
    textMuted: '#64748B',
    textInverse: '#FFFFFF',
    background: '#FFFFFF',
    backgroundSecondary: '#F8FAFC',
    tint: tintColorLight,
    icon: '#64748B',
    tabIconDefault: '#64748B',
    tabIconSelected: tintColorLight,
    card: '#FFFFFF',
    cardSecondary: '#F1F5F9',
    border: '#E2E8F0',
    borderSecondary: '#CBD5E1',
    primary: '#6366F1',
    primaryText: '#FFFFFF',
    secondary: '#8B5CF6',
    secondaryText: '#FFFFFF',
    success: '#059669',
    successText: '#FFFFFF',
    successLight: '#10B981',
    warning: '#D97706',
    warningText: '#FFFFFF',
    warningLight: '#F59E0B',
    error: '#DC2626',
    errorText: '#FFFFFF',
    errorLight: '#EF4444',
    muted: '#64748B',
    mutedText: '#FFFFFF',
    // Status colors
    online: '#059669',
    offline: '#6B7280',
    away: '#D97706',
    dnd: '#DC2626',
    // Spotify/activity colors
    spotify: '#1DB954',
    playing: '#059669',
    listening: '#1DB954',
    // Voice chat colors
    voiceConnected: '#059669',
    voiceMuted: '#6B7280',
    voiceSpeaking: '#1DB954',
  },
  dark: {
    text: '#F8FAFC',
    textSecondary: '#CBD5E1',
    textMuted: '#94A3B8',
    textInverse: '#0F172A',
    background: '#0F172A',
    backgroundSecondary: '#1E293B',
    tint: tintColorDark,
    icon: '#94A3B8',
    tabIconDefault: '#94A3B8',
    tabIconSelected: tintColorDark,
    card: '#1E293B',
    cardSecondary: '#334155',
    border: '#334155',
    borderSecondary: '#475569',
    primary: '#8B5CF6',
    primaryText: '#FFFFFF',
    secondary: '#A855F7',
    secondaryText: '#FFFFFF',
    success: '#10B981',
    successText: '#FFFFFF',
    successLight: '#34D399',
    warning: '#F59E0B',
    warningText: '#FFFFFF',
    warningLight: '#FBBF24',
    error: '#F87171',
    errorText: '#FFFFFF',
    errorLight: '#FCA5A5',
    muted: '#94A3B8',
    mutedText: '#FFFFFF',
    // Status colors
    online: '#10B981',
    offline: '#6B7280',
    away: '#F59E0B',
    dnd: '#F87171',
    // Spotify/activity colors
    spotify: '#1DB954',
    playing: '#10B981',
    listening: '#1DB954',
    // Voice chat colors
    voiceConnected: '#10B981',
    voiceMuted: '#6B7280',
    voiceSpeaking: '#1DB954',
  },
};
